/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasArea: typeof import('./src/components/CanvasArea.vue')['default']
    ChatBox: typeof import('./src/components/ai/chatBox.vue')['default']
    CodeMirrorEditor: typeof import('./src/components/codeMirrorEditor.vue')['default']
    ComponentArea: typeof import('./src/components/componentArea/componentArea.vue')['default']
    ComponentStore: typeof import('./src/components/componentStore.vue')['default']
    IframePage: typeof import('./src/components/iframePage/iframePage.vue')['default']
    MonacoEditor: typeof import('./src/components/monacoEditor.vue')['default']
    PropertyPanel: typeof import('./src/components/PropertyPanel.vue')['default']
    QwenAI: typeof import('./src/components/ai/qwenAI.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindTest: typeof import('./src/components/TailwindTest.vue')['default']
  }
}
