/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasArea: typeof import('./src/components/CanvasArea.vue')['default']
    ChatBox: typeof import('./src/components/ai/chatBox.vue')['default']
    CodeMirrorEditor: typeof import('./src/components/codeMirrorEditor.vue')['default']
    ComponentArea: typeof import('./src/components/componentArea/componentArea.vue')['default']
    ComponentStore: typeof import('./src/components/componentStore.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElementTree: typeof import('./src/components/elementTree.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    FileTree: typeof import('./src/components/ide/FileTree.vue')['default']
    FileTreeNode: typeof import('./src/components/ide/FileTreeNode.vue')['default']
    IframePage: typeof import('./src/components/iframePage/iframePage.vue')['default']
    MonacoEditor: typeof import('./src/components/monacoEditor.vue')['default']
    PageEditor: typeof import('./src/components/PageEditor.vue')['default']
    PropertyConfig: typeof import('./src/components/propertyConfig.vue')['default']
    PropertyPanel: typeof import('./src/components/PropertyPanel.vue')['default']
    QwenAI: typeof import('./src/components/ai/qwenAI.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindTest: typeof import('./src/components/TailwindTest.vue')['default']
    TemplatePage: typeof import('./src/components/templatePage.vue')['default']
    Text: typeof import('./src/components/ai/text.vue')['default']
    WebsiteGeneratorUI: typeof import('./src/components/ai/WebsiteGeneratorUI.vue')['default']
  }
}
